dist: trusty
sudo: required
language: go

services:
  - docker

env:
  global:
    # See https://github.com/go-sql-driver/mysql/wiki/Testing
    - MYSQL_TEST_USER=gotest
    - MYSQL_TEST_PASS=secret
    - MYSQL_TEST_PROT=tcp
    - MYSQL_TEST_ADDR=127.0.0.1:3307
    - MYSQL_TEST_DBNAME=gotest
    - MYSQL_TEST_CONCURRENT=1

matrix:
  include:
    # test latest stable MySQL (currently 5.7) with 4 latest Go releases + master
    - go: 1.7.x
      env: MYSQL_IMAGE=mysql:5.7
    - go: 1.8.x
      env: MYSQL_IMAGE=mysql:5.7
    - go: 1.9.x
      env: MYSQL_IMAGE=mysql:5.7
    - go: 1.10.x
      env: MYSQL_IMAGE=mysql:5.7
    - go: master
      env: MYSQL_IMAGE=mysql:5.7

    # test latest stable Go (currently 1.10.x) with all other supported MySQL versions + not yet supported 8.0
    # https://www.mysql.com/support/supportedplatforms/database.html
    - go: 1.10.x
      env: MYSQL_IMAGE=mysql:5.5
    - go: 1.10.x
      env: MYSQL_IMAGE=mysql:5.6
    - go: 1.10.x
      env: MYSQL_IMAGE=mysql:8.0

    # test latest stable Go (currently 1.10.x) with all supported MariaDB versions + not yet supported 10.3
    # https://mariadb.org/about/maintenance-policy/
    - go: 1.10.x
      env: MYSQL_IMAGE=mariadb:5.5
    - go: 1.10.x
      env: MYSQL_IMAGE=mariadb:10.0
    - go: 1.10.x
      env: MYSQL_IMAGE=mariadb:10.1
    - go: 1.10.x
      env: MYSQL_IMAGE=mariadb:10.2
    - go: 1.10.x
      env: MYSQL_IMAGE=mariadb:10.3

go_import_path: github.com/go-sql-driver/mysql

before_install:
  - go get -u github.com/mattn/goveralls

before_script:
  - sudo service mysql stop
  - docker --version
  - docker-compose --version
  - docker-compose up -d
  - .testing/wait_mysql.sh

script:
  - go test -v -covermode=count -coverprofile=coverage.out
  - go vet ./...
  - .testing/gofmt.sh

after_script:
  - $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci
